name: Cypress Web Serverest

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    name: Test Front run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Cypress dependencies
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run

      - name: Archive Cypress results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: ./cypress/videos

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://juliana-souza-franca.github.io/qa-academy-front-cypress-basico/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cypress-results

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
